version: '2'
services:
  envoy:
    image: envoyproxy/envoy:latest
    volumes:
      - ./envoy_config.yaml:/envoy.yaml
    command: envoy -c /envoy.yaml --service-cluster app-envoy --service-node app-envoy
    depends_on:
      - server
    links:
      - server
  server:
    build: .
    command: 'bundle exec ruby /app/server.rb'
  client:
    build: .
    command: 'bundle exec ruby /app/client.rb'
    environment:
      HOST: 'envoy'
      PORT: '80'
    depends_on:
      - envoy
    links:
      - envoy
